# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"process_atom": "00_core.ipynb",
         "cli_process_atom": "00_core.ipynb",
         "get_namespaces": "10_xml.ipynb",
         "re_tag": "10_xml.ipynb",
         "split_namespace_tag": "10_xml.ipynb",
         "to_be_skipped": "10_xml.ipynb",
         "get_entries": "10_xml.ipynb",
         "get_deleted_entries": "10_xml.ipynb",
         "nested_tags_separator": "10_xml.ipynb",
         "assemble_name": "10_xml.ipynb",
         "unique_name": "10_xml.ipynb",
         "set_or_append": "10_xml.ipynb",
         "entry_to_dict": "10_xml.ipynb",
         "entry_to_series": "10_xml.ipynb",
         "to_df": "10_xml.ipynb",
         "is_multivalued": "10_xml.ipynb",
         "multivalued_columns": "10_xml.ipynb",
         "str_columns": "10_xml.ipynb",
         "assembled_str_columns": "10_xml.ipynb",
         "post_process": "10_xml.ipynb",
         "to_curated_df": "10_xml.ipynb",
         "columns_depth": "10_xml.ipynb",
         "read_zip": "20_bundle.ipynb",
         "read_zips_directory": "20_bundle.ipynb",
         "flat_series_to_multiindexed_series": "30_hierarchical.ipynb",
         "flat_df_to_multiindexed_df": "30_hierarchical.ipynb",
         "pad_col_levels": "30_hierarchical.ipynb",
         "columns_containing": "30_hierarchical.ipynb",
         "File": "40_io.ipynb",
         "homogenize_multivalued": "40_io.ipynb",
         "cast_list_to_floats_or_strs": "40_io.ipynb",
         "cast_multivalued_series_to_common_type": "40_io.ipynb",
         "write": "40_io.ipynb",
         "read": "40_io.ipynb",
         "domain_discriminative_columns_paths": "50_parse.ipynb",
         "domain": "50_parse.ipynb"}

modules = ["core.py",
           "xml.py",
           "bundle.py",
           "hier.py",
           "io.py",
           "parse.py"]

doc_url = "https://manuvazquez.github.io/dlsproc/"

git_url = "https://github.com/manuvazquez/dlsproc/tree/master/"

def custom_doc_links(name): return None
