# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"process_atom": "00_core.ipynb",
         "cli_process_atom": "00_core.ipynb",
         "get_namespaces": "10_xml.ipynb",
         "re_tag": "10_xml.ipynb",
         "split_namespace_tag": "10_xml.ipynb",
         "to_be_skipped": "10_xml.ipynb",
         "get_entries": "10_xml.ipynb",
         "nested_tags_separator": "10_xml.ipynb",
         "entry_to_dict": "10_xml.ipynb",
         "entry_to_series": "10_xml.ipynb",
         "to_df": "10_xml.ipynb",
         "post_process": "10_xml.ipynb",
         "to_curated_df": "10_xml.ipynb",
         "read_zip": "20_bundle.ipynb"}

modules = ["core.py",
           "xml.py",
           "bundle.py"]

doc_url = "https://manuvazquez.github.io/dlsproc/"

git_url = "https://github.com/manuvazquez/dlsproc/tree/master/"

def custom_doc_links(name): return None
