# AUTOGENERATED! DO NOT EDIT! File to edit: 20_bundle.ipynb (unless otherwise specified).

__all__ = ['read_zip']

# Cell
import pathlib
import zipfile

import dlsproc.xml

# Cell
def read_zip(input_file: str | pathlib.Path):
    """
    Reads and parses an XML file into a `pd.DataFrame`.

    **Parameters**

    - input_file: str or Path

        Input file.

    **Returns**

    - out: pd.DataFrame

        A Pandas DataFrame with XML data.

    """

    dfs = []

    # zip file is opened
    with zipfile.ZipFile(input_file) as zip_file:

        # every file within it...
        for name in zip_file.namelist():

            # ...is opened...
            with zip_file.open(name) as f:

                # ...and processed
                dfs.append(dlsproc.xml.to_curated_df(f))

    return dfs