# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['main']

# Cell
import sys
import argparse
import pathlib

# Cell
def main():

    parser = argparse.ArgumentParser(description='Download Spanish procurement contracts')

    parser.add_argument('input_directory', default='.', help='directory with the zip-packaged XML files')

    command_line_arguments = parser.parse_args()