# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['process_atom', 'cli_process_atom', 'cli_extend_parquet_with_zip']

# Cell
import sys
import argparse
import pathlib

import dlsproc.extend

# Cell
def process_atom(input_file: str | pathlib.Path):

    print(input_file)

# Cell
def cli_process_atom() -> None:

    parser = argparse.ArgumentParser(description='Process atom file')

    parser.add_argument('input_file', type=argparse.FileType('r'), help='XML file')

    command_line_arguments = parser.parse_args()

    process_atom(command_line_arguments.input_file.name)

# Cell
def cli_extend_parquet_with_zip(args: list = None) -> None:

    parser = argparse.ArgumentParser(description='Extend existing parquet file with data from a given zip')

    parser.add_argument('history_file', type=argparse.FileType('r'), help='Parquet file')
    parser.add_argument('zip_file', type=argparse.FileType('r'), help='Zip file')
    parser.add_argument('output_file', help='Output file')

    command_line_arguments = parser.parse_args(args)

    history_file = pathlib.Path(command_line_arguments.history_file.name)
    zip_file = pathlib.Path(command_line_arguments.zip_file.name)

    output_file = pathlib.Path(command_line_arguments.output_file)
    assert not output_file.exists()

    dlsproc.extend.parquet_with_zip(history_file, zip_file, output_file)

    return command_line_arguments