# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['process_atom', 'cli_process_atom']

# Cell
import sys
import argparse
import pathlib

# Cell
def process_atom(input_file: str | pathlib.Path):

    print(input_file)

# Cell
def cli_process_atom() -> None:

    parser = argparse.ArgumentParser(description='Process atom file')

    parser.add_argument('input_file', type=argparse.FileType('r'), help='XML file')

    command_line_arguments = parser.parse_args()

    process_atom(command_line_arguments.input_file.name)