# AUTOGENERATED! DO NOT EDIT! File to edit: 40_io.ipynb (unless otherwise specified).

__all__ = ['save_df', 'load_df', 'exists', 'actual_name']

# Cell
import pathlib

import pandas as pd

import dlsproc.xml

# Cell
def save_df(df: pd.DataFrame, output_file: str | pathlib.Path):

    output_file = pathlib.Path(output_file)

    output_file.suffix == '', 'an extension-less file is expected'

    df.to_pickle(output_file.with_suffix('.pickle'))

# Cell
def load_df(input_file: str | pathlib.Path) -> pd.DataFrame:

    input_file = pathlib.Path(input_file)

    input_file.suffix == '', 'an extension-less file is expected'

    return pd.read_pickle(input_file.with_suffix('.pickle'))

# Cell
def exists(file: str | pathlib.Path) -> bool:

    file = pathlib.Path(file)

    file.suffix == '', 'an extension-less file is expected'

    return file.with_suffix('.pickle').exists()

# Cell
def actual_name(file: str | pathlib.Path) -> pathlib.Path:

    file = pathlib.Path(file)

    file.suffix == '', 'an extension-less file is expected'

    return file.with_suffix('.pickle')