# AUTOGENERATED! DO NOT EDIT! File to edit: 40_io.ipynb (unless otherwise specified).

__all__ = ['File', 'write', 'read']

# Cell
import pathlib

import pandas as pd

import dlsproc.xml

import fastcore.foundation

# Cell
class File:

    def __init__(self, stem: str | pathlib.Path):

        self.name: pathlib.Path = pathlib.Path(stem)

        assert self.name.suffix == '', 'an extension-less file is expected'

        self.name = self.name.with_suffix('.pickle')

    def __str__(self):

        return self.name.as_posix()

    def __repr__(self):

        return self.__str__()

    def exists(self) -> bool:

        return self.name.exists()

# Cell
@fastcore.foundation.patch
def write(self: File, df: pd.DataFrame):

    df.to_pickle(self.name)

# Cell
@fastcore.foundation.patch
def read(self: File) -> pd.DataFrame:

    return pd.read_pickle(self.name)