# AUTOGENERATED! DO NOT EDIT! File to edit: 50_parse.ipynb (unless otherwise specified).

__all__ = ['domain_discriminative_column_path', 'domain_into_new_column']

# Cell
import pathlib
import urllib.parse

import pandas as pd

import dlsproc.xml
import dlsproc.hier

# Cell
domain_discriminative_column_path = ['ContractFolderStatus', 'LocatedContractingParty', 'BuyerProfileURIID']

# Cell
def domain_into_new_column(df: pd.DataFrame) -> None:

    df['domain'] = df[dlsproc.hier.pad_col_levels(df, domain_discriminative_column_path)].apply(
        lambda x: urllib.parse.urlparse(x).netloc if pd.notna(x) else pd.NA)