# AUTOGENERATED! DO NOT EDIT! File to edit: 05_structure.ipynb (unless otherwise specified).

__all__ = ['nested_tags_separator', 'assemble_name']

# Cell
import re

import pandas as pd

# Cell
nested_tags_separator = ' - '

# Cell
def assemble_name(tags: list) -> str:
    """
    Assemble the name of field/column in the DataFrame from a path of nested tags.

    **Parameters**

    - tags: list

        List of tags.

    **Returns**

    - out: str

        A suitable name.

    """

    tags = filter(pd.notna, tags)
    tags = filter(lambda x: x!='', tags)

    return nested_tags_separator.join(tags)